version: "3.7"
services:
    app:
        build:
            args:
                user: worker
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: petsevice
        container_name: petservice-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - petsevice

    db:
        image: mysql:5.7
        container_name: petsevice-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        networks:
            - petsevice

    nginx:
        image: nginx:alpine
        container_name: petsevice-nginx
        restart: unless-stopped
        ports:
            - "8008:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - petsevice

networks:
    petsevice:
        driver: bridge
